---
title: "My website title"
subtitle: "My subtitle"
author: "Extra information."
output: 
  html_document:
    toc: true
    toc_depth: 2
    toc_float: true
    theme: cosmo
---
This is a test document to learn how to use **Google Docs** to generate at *website* on Github based on [this](http://www.storybench.org/convert-google-doc-rmarkdown-publish-github-pages/)tutorial

# 1. Generate this document

# 2. In tools, Open script editor

# 3. Run the convert to markdown function which sends this document in markdown version to your email.

# 4. Copy and paste the doc into RStudio

# 5. Create an index file in Rstudio

# 6. create a file named .nojekyll so that github doesn't use the jekyll engine.

To include a table of contents and spice up the site with nice typography using the **cosmo** theme, I’ve included some extra information including **toc: true **(meaning yes, I want a table of contents)**, toc_depth: 2 **(meaning only **# headlines** and **## subheds** will show up in the table of contents) and **toc_float: true** (meaning the table of contents will stay put as I scroll down).

RMarkdown websites require a _site.yml file to organize the rest of the files and add a navigation bar. In your text editor, create and save a _site.yml file following this format to name your website and include a navbar:

name: "my-website-name"
output_dir: "."
navbar:
  title: "Website title"
  left:
    - text: "Overview"
      href: index.html
    - text: "Weekly schedule"
      href: schedule.html
    - text: "Assignments"
      href: assignments.html
The output_dir: “.” is required if you want to host this website on Github pages. We do, so make sure to include it!

Notice the navbar. You can link to outside URLs or to the other pages you’ve built. Make sure to use .html. (In the next step, we’ll convert our pages from .Rmd to .html files).

Build your pages

Once you’ve finished editing your .Rmd files, you can build them into .html files. Make sure the .Rmd and .yml files are all in the same directory.

In R Studio, go to the Console pane in the bottom-left and type rmarkdown::render(“index.Rmd”) and click enter. Do the same for rmarkdown::render(“assignments.Rmd”) and rmarkdown::render(“schedule.Rmd”) or whatever you’ve named your other pages. The files should be processed by R Studio and end up in the same directory you’ve saved the .Rmd and .yml files. Open the .html files in an internet browser to double-check them.

